export const pillars = [
  "Energy Transition",
  "Nature Conservation",
  "Regenerative Agriculture",
  "Disputed Solutions",
  "Climate Change",
  "Biodiversity Loss",
  "General"
];
export const subpillars = [
  "None",
  "Renewable Power",
  "Renewable Heat",
  "Renewable Transport",
  "Energy Efficiency",
  "Land Conservation",
  "Ocean Conservation",
  "Ecosystem Restoration",
  "Wildlife Connectivity",
  "Regenerative Croplands",
  "Regenerative Rangelands",
  "Food Waste Reduction",
  "Circular Fibersheds",
  "Controversial Solutions",
  "Speculative Solutions",
  "Climate Impacts",
  "Planetary Systems",
  "Anthropogenic Causes",
  "Adaptation & Resilience",
  "Strategic Planning",
  "Accounting/MRV",
  "Deforestation",
  "Development",
  "Mining",
  "Pollution",
  "Hunting/Poaching",
  "Overfishing"
];
export const solutions = [
  "None",
  "Solar Photovoltaic",
  "Solar Thermoelectric",
  "Geothermal Power",
  "Onshore Wind",
  "Offshore Wind",
  "Wave Energy",
  "Sustainable Hydro",
  "Sust. Biomass Power",
  "Green H2 Power",
  "Advanced Nuclear",
  "Solar Heat",
  "Geothermal Heat",
  "Sust. Biomass Heat",
  "Green H2 Heat",
  "District Heat",
  "Electric Heat",
  "Green H2 Fuel",
  "Sustainable Synfuel",
  "Sustainable Biofuel",
  "Electric Transport",
  "Built Environment",
  "Transportation",
  "Transmission & Storage",
  "Industries & Services",

  "Protected Lands",
  "Conserved Lands",
  "Indigenous Tenure",
  "Urban Biodiversity",
  "Protected Seas",
  "Marine Habitats",
  "Sustainable Fisheries",
  "Marine Carbon Sinks",
  "Reforestation",
  "Forest Recovery",
  "Sustainable Forestry",
  "Grassland Restoration",
  "Wetlands Restoration",
  "Mangrove Restoration",
  "Coral/Shore Restoration",
  "Species Rewilding",
  "Land Corridors",
  "Buffers & Greenways",
  "Rivers & Streams",
  "Marine Corridors",
  "Farm Afforestation",
  "Cropland Restoration",
  "Soil Management",
  "Sustainable Biochar",
  "Sustainable Fertilizer",
  "Natural Pest Control",
  "Sustainable Rice Farming",
  "Agritecture",
  "Crop Optimization",

  "Dryland Irrigation",
  "Agroforestry",
  "Polyculture",
  "Perennial/Superfoods",
  "Seed Diversity",
  "Smallholder Farming",

  "Silvopasture",
  "Sustainable Grazing",
  "Healthy Feed",
  "Meat-free Proteins",
  "Planetarian Diet",
  "Storage & Logistics",
  "Bioregional Sourcing",
  "Food Upcycling",
  "Urban Gardening",
  "Composting",
  "Meal Planning",

  "Sustainable Fiber & Pulp",
  "Green Textiles",
  "Recycle & Reuse",

  "Conventional Nuclear",
  "Carbon Capture & Storage (CCS)",
  "Bioenergy w/ Carbon Capture (BECCS)",
  "Forest Biomass Energy",
  "Solar Radiation Management (SRM)",
  "Direct Air Capture (DAC)",

  "Disease",
  "Wildfires",
  "Extreme Heat",
  "Eco-anxiety",
  "Food/Water Insecurity",
  "Sea Level Rise",
  "Flooding/Storms",
  "Ocean Acidification",
  "Melting Ice",
  "Biodiversity Loss",
  "Drought",
  "Economic Risk",
  "Conflict & Migration",

  "Atmosphere",
  "Hyrdrosphere - Freshwater",
  "Hydrosphere - Oceans",
  "Cryosphere",
  "Lithosphere & Biosphere"
];
export const subcategories = [
  "None",
  "Monocrystalline",
  "Polycrystalline",
  "Thin-film",
  "Transparent",
  "Solar tiles",
  "Perovskite",
  "Chemicals - Pharmaceutical",
  "Chemicals - Agricultural",
  "Chemicals - Inorganic",
  "Chemicals - Fibers & Rubber",
  "Petrochemicals/Plastics",
  "Textiles & Leather",
  "Metals/Minerals",
  "Cement Production",
  "Processing - Agriculture",
  "Processing - Forestry",
  "Processing - Fisheries",
  "Water & Waste Utilities",
  "Rarity Sites",
  "Land Habitats",
  "Mammal Assemblages",
  "Intact Wilderness",
  "Climate Refugia",
  "Crops - General",
  "Asparagus & Agave (Asparagaceae)",
  "Apple, Stone Fruit & Berries (Rosaceae)",
  "Avocado (Lauraceae)",
  "Banana & Plantain",
  "Barberry & Mayapple (Berberidaceae)",
  "Bayberry (Myricaceae)",
  "Beets & Spinach (Amaranthaceae)",
  "Blueberries & Cranberries (Ericaceae)",
  "Brassicas & Capers",
  "Brazil nuts (Lecythidaceae)",
  "Buckwheat (Polygonaceae)",
  "Cactus (Cactaceae)",
  "Carrot & Celery (Apiaceae)",
  "Cassava & Rubber (Euphorbiaceae)",
  "Chestnuts (Fagaceae)",
  "Citrus (Rutaceae)",
  "Coffee (Rubiaceae)",
  "Cotton & Cacao (Malvaceae)",
  "Currant (Grossulariaceae)",
  "Fig & Jackfruit (Moraceae)",
  "Flax/Linseed (Linaceae)",
  "Ginger (Zingiberaceae)",
  "Grains/Grasses (Poaceae incl. Sugar)",
  "Grapes (Vitaceae)",
  "Guava & Clove (Myrtaceae)",
  "Hazelnuts (Betulaceae)",
  "Hemp (Cannabaceae)",
  "Honey & Pollen",
  "Legumes (Fabaceae)",
  "Lotus (Nelumbonaceae)",
  "Macadamia nuts (Proteaceae)",
  "Mangoes & Cashew (Anacardiaceae)",
  "Mangosteen & Durian",
  "Mashua & Nasturtium (Nelumbonaceae)",
  "Mint, Sage & Basil (Lamiaceae)",
  "Moringa (Moringaceae)",
  "Mushrooms",
  "Nightshades (Solanaceae incl. Tobacco)",
  "Olives (Oleaceae)",
  "Onions & Garlic (Amaryllidaceae)",
  "Palm & Coconut (Araceceae)",
  "Papaya (Caricaceae)",
  "Passion Fruit (Passifloraceae)",
  "Persimmon (Ebenanceae)",
  "Pine nuts (Pinaceae)",
  "Pineapple (Bromeliaceae)",
  "Pomegranate (Lythraceae)",
  "Poppy (Papaveraceae)",
  "Purslane (Portulacaceae)",
  "Seaweeds",
  "Sesame (Pedaliaceae)",
  "Soapberry (Sapindaceae)",
  "Soursop & Nutmeg",
  "Squash & Melons (Cucurbitaceae)",
  "Sunflower & Lettuce (Asteraceae)",
  "Taro (Araceae)",
  "Tea (Theaceae)",
  "Walnuts & Pecans (Juglandaceae)",
  "Yams & Sweet Potatoes",
  "Kiwi (Actinidiaceae)",
  "Nettle (Urticaceae)"
];

/**
 * Taxonomy configuration for global sustainability solutions.
 * 
 * Hierarchical data structure mapping solution categories to subcategories and specific solution types.
 * Each level can contain either nested objects (categories) or string arrays (specific solutions).
 * 
 * @type {Record<string, Record<string, Record<string, string[] | []>>>}
 * 
 * @example
 * const solarSolutions = solutionsData["Energy Transition"]["Renewable Power"]["Solar Photovoltaic"];
 * // Returns: ["Monocrystalline", "Polycrystalline", "Thin-film", ...]
 * 
 * @property {Object} Energy Transition - Renewable energy, heating, transport, and efficiency solutions
 * @property {Object} Nature Conservation - Land, ocean, ecosystem, and wildlife connectivity solutions
 * @property {Object} Regenerative Agriculture - Cropland, rangeland, waste reduction, and fiber solutions
 * @property {Object} Disputed Solutions - Controversial and speculative climate solutions
 * @property {Object} Climate Change - Climate impacts, planetary systems, adaptation strategies
 * @property {Object} Biodiversity Loss - Drivers of biodiversity loss
 * @property {Object} General - General category
 */
export const solutionsData: Record<string, Record<string, Record<string, string[]>>> = {
    "Energy Transition": {
        "Renewable Power": {
            "Solar Photovoltaic": [
                "Monocrystalline",
                "Polycrystalline",
                "Thin-film",
                "Transparent",
                "Solar tiles",
                "Perovskite"
            ],
            "Solar Thermoelectric": [],
            "Geothermal Power": [],
            "Onshore Wind": [],
            "Offshore Wind": [],
            "Wave Energy": [],
            "Sustainable Hydro": [],
            "Sust. Biomass Power": [],
            "Green H2 Power": [],
            "Advanced Nuclear": []
        },
        "Renewable Heat": {
            "Solar Heat": [],
            "Geothermal Heat": [],
            "Sust. Biomass Heat": [],
            "Green H2 Heat": [],
            "District Heat": [],
            "Electric Heat": []
        },
        "Renewable Transport": {
            "Green H2 Fuel": [],
            "Sustainable Synfuel": [],
            "Sustainable Biofuel": [],
            "Electric Transport": []
        },
        "Energy Efficiency": {
            "Built Environment": [],
            "Transportation": [],
            "Transmission & Storage": [],
            "Industries & Services": [
                "Chemicals - Pharmaceutical",
                "Chemicals - Agricultural",
                "Chemicals - Inorganic",
                "Chemicals - Fibers & Rubber",
                "Petrochemicals/Plastics",
                "Textiles & Leather",
                "Metals/Minerals",
                "Cement Production",
                "Processing - Agriculture",
                "Processing - Forestry",
                "Processing - Fisheries",
                "Water & Waste Utilities"
            ]
        }
    },
    "Nature Conservation": {
        "Land Conservation": {
            "Protected Lands": [],
            "Conserved Lands": [
                "Rarity Sites",
                "Land Habitats",
                "Mammal Assemblages",
                "Intact Wilderness",
                "Climate Refugia"
            ],
            "Indigenous Tenure": [],
            "Urban Biodiversity": []
        },
        "Ocean Conservation": {
            "Protected Seas": [],
            "Marine Habitats": [],
            "Sustainable Fisheries": [],
            "Marine Carbon Sinks": []
        },
        "Ecosystem Restoration": {
            "Reforestation": [],
            "Forest Recovery": [],
            "Sustainable Forestry": [],
            "Grassland Restoration": [],
            "Wetlands Restoration": [],
            "Mangrove Restoration": [],
            "Coral/Shore Restoration": [],
            "Species Rewilding": []
        },
        "Wildlife Connectivity": {
            "Land Corridors": [],
            "Buffers & Greenways": [],
            "Rivers & Streams": [],
            "Marine Corridors": []
        }
    },
    "Regenerative Agriculture": {
        "Regenerative Croplands": {
            "Farm Afforestation": [],
            "Cropland Restoration": [],
            "Soil Management": [],
            "Sustainable Biochar": [],
            "Sustainable Fertilizer": [],
            "Natural Pest Control": [],
            "Sustainable Rice Farming": [],
            "Agritecture": [],
            "Crop Optimization": [
                "Crops - General",
                "Asparagus & Agave (Asparagaceae)",
                "Apple, Stone Fruit & Berries (Rosaceae)",
                "Avocado (Lauraceae)",
                "Banana & Plantain",
                "Barberry & Mayapple (Berberidaceae)",
                "Bayberry (Myricaceae)",
                "Beets & Spinach (Amaranthaceae)",
                "Blueberries & Cranberries (Ericaceae)",
                "Brassicas & Capers",
                "Brazil nuts (Lecythidaceae)",
                "Buckwheat (Polygonaceae)",
                "Cactus (Cactaceae)",
                "Carrot & Celery (Apiaceae)",
                "Cassava & Rubber (Euphorbiaceae)",
                "Chestnuts (Fagaceae)",
                "Citrus (Rutaceae)",
                "Coffee (Rubiaceae)",
                "Cotton & Cacao (Malvaceae)",
                "Currant (Grossulariaceae)",
                "Fig & Jackfruit (Moraceae)",
                "Flax/Linseed (Linaceae)",
                "Ginger (Zingiberaceae)",
                "Grains/Grasses (Poaceae incl. Sugar)",
                "Grapes (Vitaceae)",
                "Guava & Clove (Myrtaceae)",
                "Hazelnuts (Betulaceae)",
                "Hemp (Cannabaceae)",
                "Honey & Pollen",
                "Legumes (Fabaceae)",
                "Lotus (Nelumbonaceae)",
                "Macadamia nuts (Proteaceae)",
                "Mangoes & Cashew (Anacardiaceae)",
                "Mangosteen & Durian",
                "Mashua & Nasturtium (Nelumbonaceae)",
                "Mint, Sage & Basil (Lamiaceae)",
                "Moringa (Moringaceae)",
                "Mushrooms",
                "Nightshades (Solanaceae incl. Tobacco)",
                "Olives (Oleaceae)",
                "Onions & Garlic (Amaryllidaceae)",
                "Palm & Coconut (Araceceae)",
                "Papaya (Caricaceae)",
                "Passion Fruit (Passifloraceae)",
                "Persimmon (Ebenanceae)",
                "Pine nuts (Pinaceae)",
                "Pineapple (Bromeliaceae)",
                "Pomegranate (Lythraceae)",
                "Poppy (Papaveraceae)",
                "Purslane (Portulacaceae)",
                "Seaweeds",
                "Sesame (Pedaliaceae)",
                "Soapberry (Sapindaceae)",
                "Soursop & Nutmeg",
                "Squash & Melons (Cucurbitaceae)",
                "Sunflower & Lettuce (Asteraceae)",
                "Taro (Araceae)",
                "Tea (Theaceae)",
                "Walnuts & Pecans (Juglandaceae)",
                "Yams & Sweet Potatoes",
                "Kiwi (Actinidiaceae)",
                "Nettle (Urticaceae)"
            ],
            "Dryland Irrigation": [],
            "Agroforestry": [],
            "Polyculture": [],
            "Perennial/Superfoods": [],
            "Seed Diversity": [],
            "Smallholder Farming": []
        },
        "Regenerative Rangelands": {
            "Silvopasture": [],
            "Sustainable Grazing": [],
            "Healthy Feed": [],
            "Meat-free Proteins": [],
            "Planetarian Diet": [],
            "Storage & Logistics": []
        },
        "Food Waste Reduction": {
            "Bioregional Sourcing": [],
            "Food Upcycling": [],
            "Urban Gardening": [],
            "Composting": [],
            "Meal Planning": []
        },
        "Circular Fibersheds": {
            "Sustainable Fiber & Pulp": [],
            "Green Textiles": [],
            "Recycle & Reuse": []
        }
    },
    "Disputed Solutions": {
        "Controversial Solutions": {
            "Conventional Nuclear": [],
            "Carbon Capture & Storage (CCS)": [],
            "Bioenergy w/ Carbon Capture (BECCS)": [],
            "Forest Biomass Energy": []
        },
        "Speculative Solutions": {
            "Solar Radiation Management (SRM)": [],
            "Direct Air Capture (DAC)": []
        }
    },
    "Climate Change": {
        "Climate Impacts": {
            "Disease": [],
            "Wildfires": [],
            "Extreme Heat": [],
            "Eco-anxiety": [],
            "Food/Water Insecurity": [],
            "Sea Level Rise": [],
            "Flooding/Storms": [],
            "Ocean Acidification": [],
            "Melting Ice": [],
            "Biodiversity Loss": [],
            "Drought": [],
            "Economic Risk": [],
            "Conflict & Migration": []
        },
        "Planetary Systems": {
            "Atmosphere": [],
            "Hydrosphere - Freshwater": [],
            "Hydrosphere - Oceans": [],
            "Cryosphere": [],
            "Lithosphere & Biosphere": []
        },
        "Anthropogenic Causes": {},
        "Adaptation & Resilience": {},
        "Strategic Planning": {},
        "Accounting/MRV": {}
    },
    "Biodiversity Loss": {
        "Deforestation": {},
        "Development": {},
        "Mining": {},
        "Pollution": {},
        "Hunting/Poaching": {},
        "Overfishing": {}
    },
    "General": {}
};

export const solutionDefinitions = {
  // Energy Transition – Renewable Power – Solar PV
  "Monocrystalline": "Renewable electricity derived from solar PV technology that captures photons from the sun and turns them into electric current -- Monocrystalline panels have high efficiency of 18-24%, longest avg. lifetime (33 yrs), but are more expensive than Polycrystalline.",
  "Polycrystalline": "Renewable electricity derived from solar PV technology that captures photons from the sun and turns them into electric current -- Polycrystalline panels have a lower efficiency of 13-16% efficiency, long avg. lifetime (27 yrs), and are cheaper than Monocrystalline.",
  "Thin-film": "Renewable electricity derived from solar PV technology that captures photons from the sun and turns them into electric current -- Thin film solar sheets have low efficiency 7-13% and lower energy output and a short avg. life span (15 yrs) but are flexible and relatively inexpensive.",
  "Transparent": "Renewable electricity derived from solar PV technology that captures photons from the sun and turns them into electric current -- Transparent solar sheets have very low efficiency 1-10% and lower energy output but a longer avg. life span (30 yrs) compared to thin-film.",
  "Solar tiles": "Renewable electricity derived from solar PV technology that captures photons from the sun and turns them into electric current -- Solar roof tiles are lower efficiency 10-20% but very durable for building-integrated solar with a long life span (up to 30 yrs).",
  "Perovskite": "Renewable electricity derived from solar PV technology that captures photons from the sun and turns them into electric current -- Perovskite panels are not yet currently available but have highest efficiency up to 27% and a very long avg. life span (up to 30 yrs).",

  // Renewable Power – Other
  "Solar Thermoelectric": "Renewable electricity from Concentrating Solar Power (CSP) technology produced from mirrors reflecting and concentrating sunlight to heat a central steam turbine.",
  "Geothermal Power": "Renewable power produced from a heat source within the earth.",
  "Onshore Wind": "Renewable power that is derived from wind turbines positioned on land.",
  "Offshore Wind": "Renewable power that is derived from wind turbines positioned at sea.",
  "Wave Energy": "Renewable energy harnessed from the motion of the waves.",
  "Sustainable Hydro": "Renewable power generated from smaller-scale dam projects that use less concrete, allow fish to migrate and produce significantly less of methane emissions.",
  "Sust. Biomass Power": "Renewable power created from burning biomass, most often from derived from cellulosic waste products (wood scraps, crop residue) and also municipal trash could count if it's highly efficient (e.g. Copenhagen). We do not consider burning trees for power to be sustainable.",
  "Green H2 Power": "Clean power from fuel cells (which create a current mixing H and O) where the hydrogen was produced using renewable energy -- solar, wind, hydro, geo.",
  "Advanced Nuclear": "Small Reactors, Next Gen Fission, Fusion",

  // Renewable Heat
  "Solar Heat": "Renewable heat generated from a single conversion of sunlight, such as PV panels, solar light and solar thermal energy.",
  "Geothermal Heat": "Renewable heat created from woody biomass, mostly in the form of wood pellets and woodchips.",
  "Sust. Biomass Heat": "Renewable heat produced from within the earth.",
  "Green H2 Heat": "Renewable heat derived from splitting water into hydrogen and oxygen using renewable electricity.",
  "District Heat": "A system of distributing renewable heat generated in a centralized location through a system of insulated pipes for residential and commercial heating requirements such as space heating and water heating.",
  "Electric Heat": "Electric heat made from renewable power converted to heat energy using heat pumps or other means.",

  // Renewable Transport
  "Green H2 Fuel": "Renewable H2 is a gaseous fuel that is typically transported by cooled pipelines fed into fuel cells in vehicles, that produces power to move the vehicle.",
  "Sustainable Synfuel": "Renewable fuels that can be combusted like petroleum and thus can be used in the existing fleet of jets and ships without significantly modifying their engines. Renewable power is used to convert green H2 into a stable liquid form.",
  "Sustainable Biofuel": "Renewable biofuels made from algae in a sustainable way. We do not consider fuels made from crops (e.g. soy, corn) to be sustainable as they compete for critical agricultural land used in food production.",
  "Electric Transport": "Electrified transport including trains, trams, cars, buses, and bikes which run on renewable electricity or fuel.",

  // Energy Efficiency
  "Built Environment": "Any built structure -- homes, commercial buildings, government facilities, roads & bridges, factories -- engineered to reduce the materials needed for construction (and emissions associated with those materials) + buildings are designed to require less energy for HVAC and lighting.",
  "Transportation": "Transportation efficiency includes measures that reduce dependence on automobile and air travel, namely infrastructure investments in public rail, busing, bicycles, and PEVs. It could also include policies like remote working, which reduces commuting, as well as weight reduction.",
  "Transmission & Storage": "Measures that reduce line loss -- the loss of power between the point of production and the point of consumption, including smart grids, smart meters, integrated grid storage, shedding.",

  // Industries & Services (all leaves)
  "Chemicals - Pharmaceutical": "reducing emissions of drug production",
  "Chemicals - Agricultural": "reducing emissions of fertilizer, pesticides, herbicides",
  "Chemicals - Inorganic": "reducing emissions of production of salts, acids, cleansers, lubricants, etc.",
  "Chemicals - Fibers & Rubber": "reducing emissions of synthetic rubber and fibers (e.g. polyester)",
  "Petrochemicals/Plastics": "reducing emissions of manufactoring gasoline, toluene etc. and all plastics, including plastics recycling",
  "Textiles & Leather": "reducing emissions of textiles and leather production",
  "Metals/Minerals": "reducing emissions/impacts of mining of metals and non-metallic minerals plus transformation to green steel, aluminum, etc.",
  "Cement Production": "reducing emissions of cement production (not incl. transportation and mining)",
  "Processing - Agriculture": "reducing emissions of food products manufacturing (not incl. direct agricultural emissions)",
  "Processing - Forestry": "reducing emissions of wood/paper products manufacturing (not incl. deforestation emissions)",
  "Processing - Fisheries": "reducing emissions of seafood products manufacturing",
  "Water & Waste Utilities": "reducing emissions of delivering water, treating wastewater, and operating solid waste facilities.",

  // Nature Conservation – Land
  "Protected Lands": "Layer 1 of the GSN -- land areas already protected or recognized by governments.",
  "Rarity Sites": "Layer 2 of the GSN are species rarity sites.",
  "Land Habitats": "Layer 3 of the GSN are high biodiversity areas.",
  "Mammal Assemblages": "Layer 4 of the GSN are unprotected large mammal landscapes.",
  "Intact Wilderness": "Layer 5 of the GSN are unprotected areas with a large extent of intact wilderness.",
  "Climate Refugia": "Layer 6 of the GSN are other unprotected areas that store > 50 tC per hectare.",
  "Indigenous Tenure": "Expanding and improving legal land tenure stewarded by Indigenous People or Local Communities.",
  "Urban Biodiversity": "Improving access to nature and biodiversity in urban or suburban areas.",

  // Ocean Conservation
  "Protected Seas": "Marine areas already protected or recognized by governments.",
  "Marine Habitats": "Unprotected marine areas vital to maintaining marine ecosystems.",
  "Sustainable Fisheries": "Marine areas with measures that maintain fish populations.",
  "Marine Carbon Sinks": "Marine areas important for long-term carbon storage.",

  // Ecosystem Restoration
  "Reforestation": "replanting native trees in previously forested areas.",
  "Forest Recovery": "restoring forest through natural regeneration.",
  "Sustainable Forestry": "practice of managing forests for long-term ecological health.",
  "Grassland Restoration": "Restoring grassland ecosystems.",
  "Wetlands Restoration": "Restoring wetland ecosystems.",
  "Mangrove Restoration": "replanting of native coastal mangrove trees",
  "Coral/Shore Restoration": "cleaning, repairing, or replanting coral species",
  "Species Rewilding": "reintroduction of native animal species",

  // Wildlife Connectivity
  "Land Corridors": "linear strips of land connecting wildlife areas",
  "Buffers & Greenways": "transition areas between developed land and wildlife habitat",
  "Rivers & Streams": "restoring river-adjacent habitats",
  "Marine Corridors": "known migration corridors across oceans",
  "Farm Afforestation": "Tree planting on croplands can take many forms -- from wind breaks, headgerows and pocket forests to orchards and alley cropping (with trees dividing strips of cropland.",
  "Cropland Restoration": "Returning degraded cropland back to functioning cropland or grazing lad using regenerative agriculture practices.",
  "Soil Management": "Farming practices that increase the organic carbon content of soils -- including cover crops, integrated poultry, meadow banks -- and improves soil structure and health (not incl. biochar)",
  "Sustainable Biochar": "Incorporating carbonised biomass (from controlled burning or pyrolisis) sourced from agricultural waste products, storing carbon and improving soil structure.",
  "Sustainable Fertilizer": "Fertilizer that is derived from organic sources, including organic compost, herbivore manures, purified sewage -- reducing overall need for chemical fertilizers.",
  "Natural Pest Control": "Alternatives to biocide chemicals including pesticides and herbicides.",
  "Sustainable Rice Farming": "Rice cultivated with minimal tillage using crop residue to protect the soil from erosion and loss of nutrients, reducing methane emissions.",
  "Agritecture": "Built infrastructure designed to grow crops. This can include vertical farming, advanced greenhouses, green roofs, etc.",

  "Crops - General": "Measures to optimize the placement or configuration of specific crops or other techniques to increasing overall yields and crop resilience while reducing water consumption and other inputs. Can leverage AI or data science",
  "Asparagus & Agave (Asparagaceae)": "Note: doesn't include Aloe which is Asphodelaceae family",
  "Apple, Stone Fruit & Berries (Rosaceae)": "incl. Prunus (Almonds, Pears, Cherries, Pums), Rubus (Rasberries, Blackberries), Fragaria (Stawberries), Quince, Loquat, Aronia (Chokeberry)",
  "Avocado (Lauraceae)": "also includes Cinnamon, Bay, Sassafras",
  "Banana & Plantain": "2 different families -- Musaceae & Plantaginaceae",
  "Barberry & Mayapple (Berberidaceae)": "Ranunculales order",
  "Bayberry (Myricaceae)": "Chinese Bayberry or Yangmei",
  "Beets & Spinach (Amaranthaceae)": "incl. Chard, Amaranth, Quinoa",
  "Blueberries & Cranberries (Ericaceae)": "and other Heath berries",
  "Brassicas & Capers": "2 related familes -- Brassicaceae (Broccoli, Cauliflower, Kale, Turnip, Cabbage, Bok Choi, Mustard, Rapeseed, Radish, Rutabaga) -- and Capparaceae (Capers)",
  "Brazil nuts (Lecythidaceae)": "",
  "Buckwheat (Polygonaceae)": "not actually a grain so not included in grains",
  "Cactus (Cactaceae)": "incl. Dragonfruit",
  "Carrot & Celery (Apiaceae)": "incl. Parsely, Parsnips, Fennel, Cilantro, Dill, Anise, Caraway, Cumin",
  "Cassava & Rubber (Euphorbiaceae)": "Spurge family -- Tapioca, Yuca, Manioc, also for latex production",
  "Chestnuts (Fagaceae)": "incl. Beechnuts",
  "Citrus (Rutaceae)": "incl. White Sapote, Curry, Lemon, Lime, Orange, Grapefruit, Pomelo, Kumquat",
  "Coffee (Rubiaceae)": "",
  "Cotton & Cacao (Malvaceae)": "Mallows family incl. Cotton, Cacao, Okra, Hibiscus, Kola, Kenaf",
  "Currant (Grossulariaceae)": "incl. Gooseberries, Goldenberries",
  "Fig & Jackfruit (Moraceae)": "Mulberry family -- also for latex production",
  "Flax/Linseed (Linaceae)": "",
  "Ginger (Zingiberaceae)": "incl. Turmeric, Cardamom, Galanga",
  "Grains/Grasses (Poaceae incl. Sugar)": "incl. Wheat, Corn, Rice, Barley, Millet, Sorghum, Sugar Cane, Oats, Bamboo, Teff",
  "Grapes (Vitaceae)": "",
  "Guava & Clove (Myrtaceae)": "Myrtle family includes Eucalyptus, Allspice",
  "Hazelnuts (Betulaceae)": "",
  "Hemp (Cannabaceae)": "Cannabis, Hops, Hemp (for fiber)",
  "Honey & Pollen": "derived from pollen across many plant families",
  "Legumes (Fabaceae)": "incl. Peanut, Lentil, Bean, Pea, Chickpea, Fenugreek, Jicama",
  "Lotus (Nelumbonaceae)": "",
  "Macadamia nuts (Proteaceae)": "",
  "Mangoes & Cashew (Anacardiaceae)": "incl. Pistachio",
  "Mangosteen & Durian": "2 related families -- Clusiaceae & Bombacaceae",
  "Mashua & Nasturtium (Nelumbonaceae)": "",
  "Mint, Sage & Basil (Lamiaceae)": "Mint family -- Salvia (Sage incl. Chia), Basil, Rosemary, Oregano, Thyme, Lavendar",
  "Moringa (Moringaceae)": "Moringa tree (Horseradish tree)",
  "Mushrooms": "across many different classes",
  "Nightshades (Solanaceae incl. Tobacco)": "Tomatoes, Potatoes, Peppers, Eggplants, Tobacco, Ashwaganda, Goji",
  "Olives (Oleaceae)": "",
  "Onions & Garlic (Amaryllidaceae)": "",
  "Palm & Coconut (Araceceae)": "incl. Dates, Acai",
  "Papaya (Caricaceae)": "",
  "Passion Fruit (Passifloraceae)": "",
  "Persimmon (Ebenanceae)": "incl. Black Sapote",
  "Pine nuts (Pinaceae)": "",
  "Pineapple (Bromeliaceae)": "Bromeliad family",
  "Pomegranate (Lythraceae)": "Hena family",
  "Poppy (Papaveraceae)": "Poppy seed",
  "Purslane (Portulacaceae)": "",
  "Seaweeds": "across many different classes (incl. macroalgae but not eukariotic algae)",
  "Sesame (Pedaliaceae)": "",
  "Soapberry (Sapindaceae)": "incl. Lychee, Rambutan, Maple",
  "Soursop & Nutmeg": "2 related Magnolia families - Annonaceae (incl. Custard Apple, Pawpaw, Cherimoya, Guanabana) -- and Myristicaceae (nutmeg and mace)",
  "Squash & Melons (Cucurbitaceae)": "incl. Zuchini, Cucumbers, Pumpkin, Chayote, Bittermelon, Monkfruit",
  "Sunflower & Lettuce (Asteraceae)": "incl. Chicory, Endive, Burdock, Artichoke, Sunchoke, Dandelion, Yacon, Stevia",
  "Taro (Araceae)": "",
  "Tea (Theaceae)": "Camellia",
  "Walnuts & Pecans (Juglandaceae)": "incl. Hickory",
  "Yams & Sweet Potatoes": "2 different Families -- Dioscoreaceae (incl. Ube) & Convolvulaceae",
  "Kiwi (Actinidiaceae)": "",
  "Nettle (Urticaceae)": "",

  "Dryland Irrigation": "Using technologies like drip irrigation, buns to turn desert areas with insufficient precipitation into viable croplands.",
  "Agroforestry": "Farming underneath the forest canopy or multi-story cropping on farmland that combines trees, shrubs, and herbacious plants.",
  "Polyculture": "Cultivating multiple crops, often with symbiotic properties, in the same area, which helps sequester carbon, enhance biodiversity, and improve yield resilience",
  "Perennial/Superfoods": "Cultivating perennial or biennial crops with exceptionally high nutritional value (e.g. perennial wheat, acai, goji, moringa), reduceing soil erosion and increasing carbon sequestration relative to annual crops",
  "Seed Diversity": "Efforts like seed saving and hybridization to restore heirloom crops and increase the diversity of plant types available to farmers, reversing the trend of flavorless industrialized or GMP crops bred for appearance.",
  "Smallholder Farming": "Family or community farming, generally on less than five acres (2 ha), increasing food security and allowing for micro-management of a diversity of crops adapted to a specifc region and at a lower carbon footprint",

  "Silvopasture": "Planting trees, shrubs, hedgerows on land primarily dedicated to grazing livestock (aka rangeland afforestation)",
  "Sustainable Grazing": "Raising herbivores like cattle, bison, and sheep on agricultural areas that are rotated periodically, allowing the remainder of the pasture to “rest\" so that plants can regrow, which mimicks the natural conditions that allowed both grasslands and large herbivores to thrive historically.",
  "Healthy Feed": "Feeding livestock a healthy diet that provides essential macronutrients such as protein, vitamins and minerals, and adequate fibre. This increases the health of animals, reducing dependence on antibiotics, and also reduces methane emissions from enteric fermentation (e.g. incorporating seaweed into cattle feed)",
  "Meat-free Proteins": "Replacing red meat with plant-based protein from pulses (legume crops), seaweed, moringa, insects or other high-protein sources. Note: industrialzed plant proteins can include pesticides, novel GMOs, or other chemicals and would not be considered sustainable.",
  "Planetarian Diet": "A diet based on the EAT Lancet commission that would feed 10 billion people on our current agricultural footprint. It calls for significantly reducing the intake of red meat to 1 serving per week and increasing the intake of vegetables.",
  "Storage & Logistics": "Ruducing spoiled crops on small and medium sized farms due to lack of adequate cold storage that keeps produce fresh before taken to market -- solar-powered refrigerators or low-tech cold storage solutions (e.g. excavated pits). Also logistics software to reduce food waste.",
  "Bioregional Sourcing": "Sourcing foods from local farmers to increase bioregional sustainability, resilient crops, and improve local economies. As trucking shifts to renewables this could result in less CO2 than produce frozen and shipped for long distances away.",
  "Food Upcycling": "Utilizing good produce that would be landfilled because it is cosmetically imperfect or very ripe, including food redistribution or just-in-time packaging (e.g. Misfit Markets)",
  "Urban Gardening": "Converting grass turf in urban/suburban areas (more than 40 miilion sq. miles in U.S.) to productive gardens, reducing enormous amount of water, chemicals, and petroleum fuel and boosting food security and public health. Also balcony gardening.",
  "Composting": "Assisting natural decomposition of organic matter, such as plant debris and food scraps, into a valuable fertilizer and soil amendment, contributing to soil health, reducing need for fertilizer, and reducing emissions from landfills.",
  "Meal Planning": "In OECD countries consumers throw out approx. 30% of their purchased food every year due to poor meal planning. Meal planning means \"shopping for the week\" -- taking the time to plan a balanced diet saves consumers money, boosts their health, and is a major strategy to reduce food waste.",

  "Sustainable Fiber & Pulp": "Sourcing fiber stock used to make textiles and paper from regenerative and organic agriculture practices that build soil health, increase biodiversity, protect water resources, and sequester carbon. Fiber crops contribute to deforestation (for viscose) and massive pesticide use (cotton).",
  "Green Textiles": "Processing and dying of fiber stock to make textiles requires chemicals that are extremely harmful to humans and the environment. Alternative processes and dies can use less energy and less harmful chemicals.",
  "Recycle & Reuse": "Facilitating second hand use of apparel (resue or reutilization) or recycling fibers for other industrial uses to reduce impacts of the fashion industry",
  // Disputed Solutions
  "Conventional Nuclear": "",
  "Carbon Capture & Storage (CCS)": "",
  "Bioenergy w/ Carbon Capture (BECCS)": "",
  "Forest Biomass Energy": "",
  "Solar Radiation Management (SRM)": "",
  "Direct Air Capture (DAC)": "",

  // Climate Change Impacts
  "Disease": "(public health)",
  "Wildfires": "(public health)",
  "Extreme Heat": "(public health)",
  "Eco-anxiety": "(public health)",
  "Food/Water Insecurity": "(public health)",
  "Sea Level Rise": "",
  "Flooding/Storms": "",
  "Ocean Acidification": "",
  "Melting Ice": "",
  "Biodiversity Loss": "",
  "Drought": "drying of lands, desertification, aridification",
  "Economic Risk": "investor, insurance, and market risk",
  "Conflict & Migration": "political risk and fragile nations",

  // Planetary Systems
  "Atmosphere": "hard science geophysics, IPCC working group 2, etc. ",
  "Hyrdrosphere - Freshwater": "",
  "Hydrosphere - Oceans": "",
  "Cryosphere": "",
  "Lithosphere & Biosphere": "",

  // Other Climate
  "Anthropogenic Causes": "sources of GHG pollution, companies that track emissions go here",
  "Adaptation & Resilience": "measures to adapt to climate change",
  "Strategic Planning": "",
  "Accounting/MRV": "",

  // Biodiversity Loss Causes
  "Deforestation": "",
  "Development": "converting non-forest lands incl. for farmland",
  "Mining": "",
  "Pollution": "Air, Water, Soil, Light, Sound",
  "Hunting/Poaching": "",
  "Overfishing": "",

  // Catch-all
  "General": "Anything that doesn't fit into the above (please add tags to describe)"
};

